# Generated by Django 5.2.7 on 2026-08-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category_tag', models.CharField(default='INDUSTRY INSIGHTS', max_length=100)),
                ('teaser', models.TextField()),
                ('author', models.CharField(default='Grillista Corporate Research', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('photo_url', models.CharField(default='assets/images/logo.jpg', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('model_type', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', max_length=20)),
                ('url', models.CharField(default='assets/images/store_bg.jpg', max_length=500)),
                ('category', models.CharField(default='interiors', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('burgers', 'Veg Flame Burgers'), ('wraps', 'Tandoori Wraps'), ('bites', 'Charred Soya Starters'), ('sides', 'Loaded Sides'), ('shakes', 'Energy Shakes')], default='burgers', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(default='assets/images/burger.jpg', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(default='UP', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE NOW', 'AVAILABLE NOW'), ('TERRITORY BOOKED', 'TERRITORY BOOKED'), ('STORES LIVE', 'STORES LIVE')], default='AVAILABLE NOW', max_length=50)),
                ('population', models.CharField(blank=True, max_length=50, null=True)),
                ('daily_orders', models.CharField(blank=True, max_length=50, null=True)),
                ('min_area_sqft', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('net_margin', models.CharField(default='32% Net Margin', max_length=50)),
                ('quote', models.TextField()),
            ],
        ),
    ]
